version: 2

sources:
  - name: sequence
    database: COBRE_GOLD_DB
    schema: SEQUENCE
    tables:
      - name: INVOICES
      - name: CUSTOMERS
      - name: INVOICE_LINE_ITEMS
      - name: PRICES
      - name: BILLING_SCHEDULE_PHASE_PRICES
      - name: USAGE_METRICS

  - name: datawarehouse
    database: COBRE_GOLD_DB
    schema: DATAWAREHOUSE
    tables:
      - name: MONEY_MOVEMENTS 