name: 'dbt_cobre_data_hub'
version: '1.0.0'
config-version: 2

profile: 'cobre_data_hub'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  client_id: ["cli_3qjccqlafg", "cli_bfvtnspza2", "cli_qqor9ztpcp", "cli_in4j1s6zuq", "cli_bdgczxcwd0", "cli_th5ezoyh3w", 
              "DOD339","TNA629", "YOY356", "FOF452", "GIL367", "MEK368", "MRC343", "PBO507", "RMR357", "YGO355", "TFR430", 
              "ZZA552", "cli_0bkxmugbsn", "TRE721", "TAO366", "cli_w1iczcqrox", "TST707", "RNR687", "RNR687", "EES720", "ASD713", "ASD713", "TNA629"]
  billing_period_start: "2025-04-01"
  billing_period_end: "2025-06-30"

models:
  cobre_data_hub:
    mms_billing:
      staging:
        +materialized: table
        +schema: dbt_{{ env }}
      intermediate:
        +materialized: table
        +schema: dbt_{{ env }}
      marts:
        +materialized: table
        +schema: dbt_{{ env }}
