name: 'dbt_cobre_data_hub'
version: '1.0.0'
config-version: 2

profile: 'cobre_data_hub'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  client_id: ["cli_3qjccqlafg", "cli_bfvtnspza2", "cli_qqor9ztpcp", "cli_in4j1s6zuq", "cli_bdgczxcwd0", "cli_th5ezoyh3w", "DOD339"]
  billing_period_start: "2025-04-01"
  billing_period_end: "2025-06-30"

models:
  cobre_data_hub:
    mms_billing:
      staging:
        +materialized: view
        +schema: dbt_{{ env }}
      intermediate:
        +materialized: view
        +schema: dbt_{{ env }}
      marts:
        +materialized: table
        +schema: dbt_{{ env }}
