tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: accountadmin
      database: COBRE_GOLD_DB
      schema: DBT_DEV
      warehouse: COMPUTE_WH
    prod:
      type: snowflake
      role: accountadmin
      database: COBRE_GOLD_DB
      schema: DBT_PROD
      warehouse: COMPUTE_WH