cobre_data_hub:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: wleujpv-cobre
      user: ronalm@cobre.co
      role: DATA_DEV_L0
      database: COBRE_GOLD_DB
      schema: DBT_DEV
      warehouse: COMPUTE_WH
      threads: 1
    prod:
      type: snowflake
      account: wleujpv-cobre
      user: ronalm@cobre.co
      role: DATA_DEV_L0
      database: COBRE_GOLD_DB
      schema: DBT_PROD
      warehouse: COMPUTE_WH
      threads: 1

