cobre_data_hub:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: DATA_DEV_L0
      database: COBRE_GOLD_DB
      schema: DBT_DEV
      warehouse: COMPUTE_WH
    prod:
      type: snowflake
      role: DATA_DEV_L0
      database: COBRE_GOLD_DB
      schema: DBT_PROD
      warehouse: COMPUTE_WH