version: 2

models:
  - name: invoice_pricing
    description: "Modelo para calcular los precios de facturación de las facturas."
    columns:
      - name: CUSTOMER_ALIASES
        description: "Alias del cliente."
      - name: INVOICE_ID
        description: "ID de la factura."
      - name: MONTH
        description: "Mes del periodo de facturación."
      - name: TITLE
        description: "Título del ítem de la factura."
      - name: PRODUCT_NAME
        description: "Nombre del producto."
      - name: USAGE_METRIC
        description: "Métrica de uso."
      - name: PRICE_MINIMUM_AMOUNT
        description: "Monto mínimo del precio."
      - name: CONSUMES_SAAS
        description: "Indica si consume SaaS."
      - name: QUANTITY
        description: "Cantidad del ítem."
      - name: RATE
        description: "Tasa aplicada al ítem."
      - name: PROPERTY_FILTERS
        description: "Filtros de propiedad aplicados."
      - name: PRICE_STRUCTURE
        description: "Estructura de precios."
      - name: CURRENCY
        description: "Moneda utilizada."
      - name: NET_TOTAL
        description: "Total neto del ítem."
      - name: GROSS_TOTAL
        description: "Total bruto del ítem."
      - name: CALCULATED_AT
        description: "Fecha de cálculo del ítem."
  - name: payouts_mms
    description: "Modelo para calcular los pagos MMS."
    columns:
      - name: AMOUNT
        description: "Monto de la transacción."
      - name: MM_ID
        description: "ID del movimiento de dinero."
      - name: CLIENT_ID
        description: "ID del cliente."
      - name: EVENTTYPE
        description: "Tipo de evento."
      - name: EVENTTIMESTAMP
        description: "Marca de tiempo del evento."
      - name: FLOW
        description: "Flujo de la transacción."
      - name: TRANSACTION_TYPE
        description: "Tipo de transacción."
      - name: ORIGINATION_SYSTEM
        description: "Sistema de origen de la transacción."
      - name: SOURCE_ACCOUNT_TYPE
        description: "Tipo de cuenta de origen."
      - name: TRANSFER_METHOD
        description: "Método de transferencia."
      - name: DESTINATION_BANK
        description: "Banco de destino."
      - name: ORIGIN_BANK
        description: "Banco de origen."
      - name: COUNTRY
        description: "País de la transacción." 